version: "3.9"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - listing-service
      - transaction-service

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway

  user-service:
    build: ./services/user-service
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=user-db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=users
    depends_on:
      - user-db

  listing-service:
    build: ./services/listing-service
    ports:
      - "5002:5002"
    environment:
      - DB_HOST=listing-db
      - DB_USER=listing
      - DB_PASS=password
      - DB_NAME=listings
    depends_on:
      - listing-db

  transaction-service:
    build: ./services/transaction-service
    ports:
      - "5003:5003"
    environment:
      - DB_HOST=transaction-db
      - DB_USER=transaction
      - DB_PASS=password
      - DB_NAME=transactions
    depends_on:
      - transaction-db

  user-db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    ports:
      - "5432:5432"

  listing-db:
    image: postgres:14
    environment:
      POSTGRES_USER: listing
      POSTGRES_PASSWORD: password
      POSTGRES_DB: listings
    ports:
      - "5433:5432"

  transaction-db:
    image: postgres:14
    environment:
      POSTGRES_USER: transaction
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transactions
    ports:
      - "5434:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
